CREATE SCHEMA `tracer` ;
CREATE TABLE `tracer`.`student` (
  `idstudent` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(225) NOT NULL,
  `lastname` VARCHAR(225) NOT NULL,
  `studentno` VARCHAR(45) NOT NULL,
  `course` VARCHAR(225) NOT NULL,
  `age` INT NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(225) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(225) NOT NULL,
  `timein` DATETIME NOT NULL,
  PRIMARY KEY (`idstudent`));
CREATE TABLE `tracer`.`prof` (
  `idprof` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(225) NOT NULL,
  `lastname` VARCHAR(225) NOT NULL,
  `profno` VARCHAR(45) NOT NULL,
  `dept` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(225) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(225) NOT NULL,
  `timein` DATETIME NOT NULL,
  PRIMARY KEY (`idprof`));
CREATE TABLE `tracer`.`schoolstaff` (
  `idschoolstaff` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(225) NOT NULL,
  `lastname` VARCHAR(225) NOT NULL,
  `workno` VARCHAR(45) NOT NULL,
  `work` VARCHAR(225) NOT NULL,
  `age` INT NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(225) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(225) NOT NULL,
  `timein` DATETIME NOT NULL,
  PRIMARY KEY (`idschoolstaff`));
CREATE TABLE `tracer`.`maintenance` (
  `idmaintenance` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `idno` VARCHAR(45) NOT NULL,
  `work` VARCHAR(225) NOT NULL,
  `age` INT NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(225) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(225) NOT NULL,
  `timein` DATETIME NOT NULL,
  PRIMARY KEY (`idmaintenance`));
CREATE TABLE `tracer`.`vendor` (
  `idvendor` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `stallno` VARCHAR(45) NOT NULL,
  `stallname` VARCHAR(225) NOT NULL,
  `age` INT NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(225) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(225) NOT NULL,
  `timein` DATETIME NOT NULL,
  PRIMARY KEY (`idvendor`));
CREATE TABLE `tracer`.`visitor` (
  `idvisitor` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(225) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(225) NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `timein` DATETIME NOT NULL,
  PRIMARY KEY (`idvisitor`));
CREATE TABLE `tracer`.`logistics` (
  `idlogistics` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `plateno` VARCHAR(45) NOT NULL,
  `company` VARCHAR(225) NOT NULL,
  `age` INT NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(225) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(225) NOT NULL,
  `timein` DATETIME NOT NULL,
  PRIMARY KEY (`idlogistics`));
CREATE TABLE `tracer`.`fooddelivery` (
  `idfooddelivery` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `plateno` VARCHAR(45) NOT NULL,
  `company` VARCHAR(225) NOT NULL,
  `age` INT NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(225) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(225) NOT NULL,
  `timein` DATETIME NOT NULL,
  PRIMARY KEY (`idfooddelivery`));